### ISSUE TITLE
jHandles, programmatically moving layers

### ISSUE THREAD

**Issue by rads17** [caleb531/jcanvas#210]
Hey Caleb,

I've been using jcanvas and jhandles for last few weeks and it has been really great, so thank you for all the time and hard work you have put into it!

I have found a problem that is giving me a bit of a headache, I tried to reproduce it in the sandbox for convience and I actually ending up reproducing the reciprocal of my problem, but a problem nonetheless.

Basically the issue is when I try to move a layer that has handles, only the handles move and the layer doesn't. When I went to reproduce this in the sandbox I got the opposite affect, the layer moved but the  handles didn't follow, but I feel like the two issues are related.

```
// Add rectangle layer w/o drawing
$('canvas').addLayer({
  name:"foo",
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  // Define handle properties
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10
  },
  handlestop:function(layer){
    console.log(layer.width, layer.height);
  }
})
// Redraw layers to ensure handles are on top of rectangle
.drawLayers();

var $canvas = $('canvas');
                
var layer = $canvas.getLayer("foo");

console.log("start coords: ", layer.x, layer.y);

setTimeout(function(){
  $canvas.setLayer(layer, {
    x:100,
    y:100
  }).drawLayers();

},500);
```

**Comment by caleb531** [comment]
What version of jCanvas Handles are you using? I just pushed a fix for this exact problem earlier this week.

**Comment by rads17** [comment]
I am using jCanvas Handles v15.09.25, also the sandbox still has the error, and the download link is still for v15.03.31

**Comment by caleb531** [comment]
You were probably viewing a cached version of the script. If you refresh the page, it should be the latest:
http://projects.calebevans.me/jcanvas/resources/jcanvas/plugins/jcanvas-handles.js <http://projects.calebevans.me/jcanvas/resources/jcanvas/plugins/jcanvas-handles.js>

Caleb

**Comment by rads17** [comment]
Ahhh you're right and refreshing the sandbox shows it as fixed, but still doesn't explain why in my program, which was using the latest the handles move to the new location but the layer doesn't.. I will try to reproduce it in the sandbox

**Comment by rads17** [comment]
It's very odd, see my issue is I am implementing an undo/redo by saving the x, and y of the layer before/after it is moved which works perfectly, except for when I delete the layer, undo the delete and then try to undo the movement. What happens is the handles move, and if I log the layer it says x and y are correctly moved, and the handles would suggest that, but the layer isn't actually moved. Do I also need to keep track of / change dx and dy? Or perhaps another attribute of the layer?

**Comment by caleb531** [comment]
You shouldn't need to. However, as you suggested earlier, providing me a simplified case that reproduces the issue (something I can throw into the Sandbox and verify) would be greatly appreciated.

**Comment by rads17** [comment]
Ok here, if you pardon the terrible usage of setTimeout, this code demonstrates the exact issue.

```
// Add rectangle layer w/o drawing
$('canvas').addLayer({
  name:"foo",
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  // Define handle properties
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10
  },
  handlestop:function(layer){
    console.log(layer.width, layer.height);
  }
})
// Redraw layers to ensure handles are on top of rectangle
.drawLayers();

var $canvas = $('canvas');
                
var layer = $canvas.getLayer("foo");

console.log("start coords: ", layer.x, layer.y);
var oldx = layer.x;
var oldy = layer.y;
setTimeout(function(){
  $canvas.setLayer(layer, {
    x:100,
    y:100
  }).drawLayers();

},500);


setTimeout(function() {
  var layercopy = layer;
  $canvas.removeLayer(layer).drawLayers();
  setTimeout(function() {
    $canvas.addLayer(layercopy).drawLayers();
    
    setTimeout(function() {
      $canvas.setLayer(layer, {
   		 x:oldx,
   		 y:oldy
 	  }).drawLayers();
     },500);
  },500);
  
}, 1000);

```

**Comment by caleb531** [comment]
Instead of immediately changing the properties of a newly-created layer, you can kill two birds with one stone (so to speak) and update the layer properties when you recreate the layer. This fixed the issue for me in the Sandbox.

Here's the new code:

```javascript
// Add rectangle layer w/o drawing
$('canvas').addLayer({
  name:"foo",
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  // Define handle properties
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10
  },
  handlestop:function(layer){
    console.log(layer.width, layer.height);
  }
})
// Redraw layers to ensure handles are on top of rectangle
.drawLayers();

var $canvas = $('canvas');

var layer = $canvas.getLayer("foo");

console.log("start coords: ", layer.x, layer.y);
var oldx = layer.x;
var oldy = layer.y;
setTimeout(function(){
  $canvas.setLayer(layer, {
    x:100,
    y:100
  }).drawLayers();

},500);


setTimeout(function() {
  var layercopy = layer;
  $canvas.removeLayer(layer).drawLayers();
  setTimeout(function() {
    
    $canvas.addLayer($.extend(layercopy, {
      x:oldx,
      y:oldy
    })).drawLayers();
                     
  },500);

}, 1000);
```

**Comment by rads17** [comment]
Strange that that works, but unfortunately that isn't the proper functionality. The act of deleting the layer, and the act of moving the layer are 2 separate undo's.

**Comment by caleb531** [comment]
Figured it out.

Don't assume that the layer you pass into `addLayer()` is the layer that's actually created and stored internally by jCanvas. You should retrieve the layer again using `getLayer()` or just let jCanvas do that work for you by passing the layer's `name` to `setLayer()` (instead of the object itself):

Here's your most recent code with the working changes. Note that I am passing `layer.name` to `setLayer()` instead of the layer object itself. I also decided to eliminate `layercopy`, since that's not necessary.

```javascript
// Add rectangle layer w/o drawing
$('canvas').addLayer({
  name:"foo",
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  // Define handle properties
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10
  },
  handlestop:function(layer){
    console.log(layer.width, layer.height);
  }
})
// Redraw layers to ensure handles are on top of rectangle
.drawLayers();

var $canvas = $('canvas');

var layer = $canvas.getLayer("foo");

console.log("start coords: ", layer.x, layer.y);
var oldx = layer.x;
var oldy = layer.y;
setTimeout(function(){
  $canvas.setLayer(layer, {
    x:100,
    y:100
  }).drawLayers();

},500);


setTimeout(function() {
  $canvas.removeLayer(layer).drawLayers();
  setTimeout(function() {
    $canvas.addLayer(layer).drawLayers();

    setTimeout(function() {
      $canvas.setLayer(layer.name, {
         x:oldx,
         y:oldy
      }).drawLayers();
     },500);
  },500);

}, 1000);
```

**Comment by rads17** [comment]
Excellent, thank you Caleb works perfectly.
